// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt-WtzbWzTKfd-C2k8_JOmMNr2xa14bZ4',
    appId: '1:648453053928:web:45ff75d98389732dbf985d',
    messagingSenderId: '648453053928',
    projectId: 'spacenews-core',
    authDomain: 'spacenews-core.firebaseapp.com',
    storageBucket: 'spacenews-core.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVE8p8qwdAd-xMYWC5u1t1Ua17Zi0WBaA',
    appId: '1:648453053928:android:be7bb48ab13ad3bfbf985d',
    messagingSenderId: '648453053928',
    projectId: 'spacenews-core',
    storageBucket: 'spacenews-core.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAowSppT7in3mXJwg2Ozd0HaTvhBdbkxmM',
    appId: '1:648453053928:ios:1067274f4c927183bf985d',
    messagingSenderId: '648453053928',
    projectId: 'spacenews-core',
    storageBucket: 'spacenews-core.firebasestorage.app',
    iosBundleId: 'com.example.remidi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAowSppT7in3mXJwg2Ozd0HaTvhBdbkxmM',
    appId: '1:648453053928:ios:1067274f4c927183bf985d',
    messagingSenderId: '648453053928',
    projectId: 'spacenews-core',
    storageBucket: 'spacenews-core.firebasestorage.app',
    iosBundleId: 'com.example.remidi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt-WtzbWzTKfd-C2k8_JOmMNr2xa14bZ4',
    appId: '1:648453053928:web:c335bb3396602e89bf985d',
    messagingSenderId: '648453053928',
    projectId: 'spacenews-core',
    authDomain: 'spacenews-core.firebaseapp.com',
    storageBucket: 'spacenews-core.firebasestorage.app',
  );
}
